# Generated by Django 2.2 on 2021-11-29 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211129_0715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingrdient',
            new_name='ingrdients',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
    ]
